language: java
addons:
  sonarcloud:
    organization: pjcouldbe-github # the key of the org you chose at step #3
    token:
      secure: 05a965bece8d6fc85e42e2f0ea23d6e896df5cfe # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
